name: Run Tests

on:
  push:
    branches: [ main, '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-local:
    name: Test in Local Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
  
  test-docker:
    name: Test in Docker Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and run tests in Docker
      run: |
        # Create a Dockerfile.test that doesn't run prune --production so tests can run
        cat > Dockerfile.test << EOF
        FROM node:16-alpine
        WORKDIR /usr/src/app
        COPY package*.json ./
        RUN npm ci
        COPY . .
        CMD ["npm", "test"]
        EOF
        
        # Build and run the test container
        docker build -f Dockerfile.test -t ms-graph-teams-app-test .
        docker run --rm ms-graph-teams-app-test